/**
 * voltage_monitor.h
 * Header file for voltage monitoring module
 * AUTO-GENERATED BY AI
 */

#ifndef VOLTAGE_MONITOR_H
#define VOLTAGE_MONITOR_H

#include <stdint.h>

/* Function prototypes */
int voltage_monitor_init(void);
float voltage_read_capacitor(void);
int voltage_check_status(float voltage);
float voltage_get_deviation(float voltage);

#endif /* VOLTAGE_MONITOR_H */
