/**
 * voltage_monitor.c
 * 
 * Firmware voltage monitoring thresholds for Catalyst 9300 Power Module
 * 
 * AUTO-GENERATED BY AI - Story: SCRUM-23
 * Change: Capacitor substitution CAP-X123 → CAP-Y456
 * Reason: EOL replacement with 2% voltage variance
 */

#ifndef VOLTAGE_MONITOR_H
#define VOLTAGE_MONITOR_H

/*
 * Capacitor Voltage Thresholds - Updated for CAP-Y456 (Murata)
 * 
 * Previous (CAP-X123): 16.0V nominal
 * New (CAP-Y456): 16.3V nominal (+2%)
 */

#define CAPACITOR_VOLTAGE_NOM    16.3f
#define CAPACITOR_VOLTAGE_MIN    15.48f
#define CAPACITOR_VOLTAGE_MAX    17.12f

#define VOLTAGE_CHECK_INTERVAL_MS  100
#define VOLTAGE_WARNING_THRESHOLD  0.03f
#define VOLTAGE_CRITICAL_THRESHOLD 0.05f

typedef enum {
    VOLTAGE_STATUS_OK = 0,
    VOLTAGE_STATUS_WARNING = 1,
    VOLTAGE_STATUS_CRITICAL = 2,
    VOLTAGE_STATUS_OUT_OF_RANGE = 3
} VoltageStatus_t;

int voltage_monitor_init(void);
float voltage_read_capacitor(void);
VoltageStatus_t voltage_check_status(float voltage);
float voltage_get_deviation(float voltage);

#endif

#include <stdio.h>
#include <math.h>

static int _initialized = 0;

int voltage_monitor_init(void) {
    _initialized = 1;
    printf("[VOLTAGE_MONITOR] Initialized for CAP-Y456\n");
    printf("[VOLTAGE_MONITOR] Range: %.2fV - %.2fV\n", CAPACITOR_VOLTAGE_MIN, CAPACITOR_VOLTAGE_MAX);
    return 0;
}

float voltage_read_capacitor(void) {
    return CAPACITOR_VOLTAGE_NOM;
}

VoltageStatus_t voltage_check_status(float voltage) {
    if (voltage < CAPACITOR_VOLTAGE_MIN || voltage > CAPACITOR_VOLTAGE_MAX) {
        return VOLTAGE_STATUS_OUT_OF_RANGE;
    }
    float deviation = fabsf(voltage_get_deviation(voltage));
    if (deviation >= VOLTAGE_CRITICAL_THRESHOLD) return VOLTAGE_STATUS_CRITICAL;
    if (deviation >= VOLTAGE_WARNING_THRESHOLD) return VOLTAGE_STATUS_WARNING;
    return VOLTAGE_STATUS_OK;
}

float voltage_get_deviation(float voltage) {
    return (voltage - CAPACITOR_VOLTAGE_NOM) / CAPACITOR_VOLTAGE_NOM;
}
