/**
 * voltage_monitor.c
 * 
 * Firmware voltage monitoring thresholds for Catalyst 9300 Power Module
 * 
 * AUTO-GENERATED BY AI - Story: PLM-176
 * Change: Capacitor substitution CAP-X123 → CAP-Y456
 * Reason: EOL replacement with 2% voltage variance
 * 
 * IMPORTANT: This code requires review before deployment
 */

#ifndef VOLTAGE_MONITOR_H
#define VOLTAGE_MONITOR_H

/*
 * Capacitor Voltage Thresholds
 * Updated for CAP-Y456 (Murata) - replaces EOL part CAP-X123
 * 
 * Previous values (CAP-X123):
 *   - CAPACITOR_VOLTAGE_NOM: 16.0V
 *   - CAPACITOR_VOLTAGE_MIN: 15.2V
 *   - CAPACITOR_VOLTAGE_MAX: 16.8V
 *
 * New values (CAP-Y456):
 *   - Nominal voltage: 16.3V (+2% from original)
 *   - Tolerance: ±5% per Cisco Thermal Standard-7
 */

#define CAPACITOR_VOLTAGE_NOM    16.3f   /* Nominal voltage - CAP-Y456 */
#define CAPACITOR_VOLTAGE_MIN    15.48f   /* Minimum threshold (5% below nominal) */
#define CAPACITOR_VOLTAGE_MAX    17.12f   /* Maximum threshold (5% above nominal) */

/* Voltage monitoring interval in milliseconds */
#define VOLTAGE_CHECK_INTERVAL_MS  100

/* Alert thresholds */
#define VOLTAGE_WARNING_THRESHOLD  0.03f  /* 3% deviation triggers warning */
#define VOLTAGE_CRITICAL_THRESHOLD 0.05f  /* 5% deviation triggers critical alert */

/*
 * Voltage status enumeration
 */
typedef enum {
    VOLTAGE_STATUS_OK = 0,
    VOLTAGE_STATUS_WARNING = 1,
    VOLTAGE_STATUS_CRITICAL = 2,
    VOLTAGE_STATUS_OUT_OF_RANGE = 3
} VoltageStatus_t;

/*
 * Function prototypes
 */

/**
 * @brief Initialize voltage monitoring for capacitor
 * @return 0 on success, -1 on failure
 */
int voltage_monitor_init(void);

/**
 * @brief Read current capacitor voltage
 * @return Current voltage in volts
 */
float voltage_read_capacitor(void);

/**
 * @brief Check voltage against thresholds
 * @param voltage Current voltage reading
 * @return VoltageStatus_t indicating voltage status
 */
VoltageStatus_t voltage_check_status(float voltage);

/**
 * @brief Get voltage deviation percentage from nominal
 * @param voltage Current voltage reading
 * @return Deviation percentage (positive or negative)
 */
float voltage_get_deviation(float voltage);

#endif /* VOLTAGE_MONITOR_H */


/*
 * Implementation
 */

#include <stdio.h>
#include <math.h>

static int _initialized = 0;

int voltage_monitor_init(void) {
    /* Initialize ADC for voltage monitoring */
    /* Hardware-specific initialization would go here */
    _initialized = 1;
    
    printf("[VOLTAGE_MONITOR] Initialized for CAP-Y456\n");
    printf("[VOLTAGE_MONITOR] Nominal: %.2fV, Range: %.2fV - %.2fV\n",
           CAPACITOR_VOLTAGE_NOM, CAPACITOR_VOLTAGE_MIN, CAPACITOR_VOLTAGE_MAX);
    
    return 0;
}

float voltage_read_capacitor(void) {
    /* Read voltage from ADC */
    /* Placeholder - actual implementation reads from hardware */
    return CAPACITOR_VOLTAGE_NOM;  /* Simulated reading */
}

VoltageStatus_t voltage_check_status(float voltage) {
    if (voltage < CAPACITOR_VOLTAGE_MIN || voltage > CAPACITOR_VOLTAGE_MAX) {
        return VOLTAGE_STATUS_OUT_OF_RANGE;
    }
    
    float deviation = fabsf(voltage_get_deviation(voltage));
    
    if (deviation >= VOLTAGE_CRITICAL_THRESHOLD) {
        return VOLTAGE_STATUS_CRITICAL;
    } else if (deviation >= VOLTAGE_WARNING_THRESHOLD) {
        return VOLTAGE_STATUS_WARNING;
    }
    
    return VOLTAGE_STATUS_OK;
}

float voltage_get_deviation(float voltage) {
    return (voltage - CAPACITOR_VOLTAGE_NOM) / CAPACITOR_VOLTAGE_NOM;
}
